[project]
name = "hubspot-import"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "auth>=1.3.0",
    "authlib==1.3.2",
    "dotenv>=0.9.9",
    "hubspot-api-client>=12.0.0",
    "streamlit[auth]>=1.52.1",
]
